language: go
sudo: false
branches:
    only:
        - edition

go:
    - 1.5.2
    - 1.5.3
    - tip

install:
    - go get github.com/spf13/hugo

script:
    - bin/setup_theme
    - bin/compile
    - bin/publish
